package com.daviddunn.retirementplanner.domain.tax;

import com.daviddunn.retirementplanner.domain.rules.GovernmentRules;
import com.daviddunn.retirementplanner.domain.rules.SocialSecurityTaxRules;
import com.daviddunn.retirementplanner.domain.rules.FilingStatus;

import java.math.BigDecimal;
import java.util.Objects;

public final class SocialSecurityTaxCalculator {

    private static final BigDecimal FIFTY_PERCENT =
            new BigDecimal("0.50");

    private static final BigDecimal EIGHTY_FIVE_PERCENT =
            new BigDecimal("0.85");

    public BigDecimal calculateTaxableBenefits(
            TaxIncome taxIncome,
            FilingStatus filingStatus,
            GovernmentRules governmentRules) {

        Objects.requireNonNull(
                taxIncome,
                "Tax income is required.");

        Objects.requireNonNull(
                filingStatus,
                "Filing status is required.");

        Objects.requireNonNull(
                governmentRules,
                "Government rules are required.");

        BigDecimal socialSecurity =
                taxIncome.getSocialSecurityIncome();

        if (socialSecurity.signum() == 0) {
            return BigDecimal.ZERO;
        }

        SocialSecurityTaxRules rules =
                governmentRules.getSocialSecurityTaxRules(
                        filingStatus);

        BigDecimal halfSocialSecurity =
                socialSecurity.multiply(
                        FIFTY_PERCENT);

        BigDecimal combinedIncome =
                taxIncome
                        .getOrdinaryIncomeBeforeSocialSecurity()
                        .add(halfSocialSecurity);

        BigDecimal firstThreshold =
                rules.getFirstThreshold();

        BigDecimal secondThreshold =
                rules.getSecondThreshold();

        /*
         * Combined income at or below the first
         * threshold produces no taxable
         * Social Security benefits.
         */
        if (combinedIncome.compareTo(
                firstThreshold) <= 0) {

            return BigDecimal.ZERO;
        }

        /*
         * Between the first and second thresholds,
         * up to 50% of Social Security is taxable.
         */
        if (combinedIncome.compareTo(
                secondThreshold) <= 0) {

            BigDecimal amountAboveFirstThreshold =
                    combinedIncome.subtract(
                            firstThreshold);

            return amountAboveFirstThreshold
                    .multiply(FIFTY_PERCENT)
                    .min(halfSocialSecurity);
        }

        /*
         * Above the second threshold:
         *
         * 85% of the amount above the second
         * threshold is added to the taxable amount
         * generated by the first tier.
         */
        BigDecimal firstTierMaximum =
                secondThreshold
                        .subtract(firstThreshold)
                        .multiply(FIFTY_PERCENT)
                        .min(halfSocialSecurity);

        BigDecimal amountAboveSecondThreshold =
                combinedIncome.subtract(
                        secondThreshold);

        BigDecimal taxableBenefits =
                firstTierMaximum.add(
                        amountAboveSecondThreshold
                                .multiply(
                                        EIGHTY_FIVE_PERCENT));

        /*
         * No more than 85% of total Social Security
         * benefits can be taxable.
         */
        BigDecimal maximumTaxableBenefits =
                socialSecurity.multiply(
                        EIGHTY_FIVE_PERCENT);

        return taxableBenefits.min(
                maximumTaxableBenefits);
    }
}